import { useEffect, useState } from 'react'
import { Scale, RefreshCw } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useToast } from '../lib/toast'

type Variant={id:string;color:string|null;product:{nombre:string;sku:string|null}|null}
type Row={proveedor_id:string;proveedor:string;ultima_compra:string;ultimo_costo:number;costo_minimo:number;costo_promedio:number;unidades_compradas:number}
const money=(v:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v||0))

export default function ComparadorProveedores(){
 const {showToast}=useToast();const [variants,setVariants]=useState<Variant[]>([]);const [variantId,setVariantId]=useState('');const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(false)
 const loadVariants=async()=>{const {data,error}=await supabase.from('product_variants').select('id,color,product:products(nombre,sku)').order('created_at',{ascending:false}).limit(700);if(error){showToast(error.message,'error');return}setVariants((data as unknown as Variant[])||[])}
 useEffect(()=>{loadVariants()},[])
 const comparar=async(id=variantId)=>{if(!id){setRows([]);return}setLoading(true);const {data,error}=await supabase.rpc('comparar_costos_proveedores_admin',{p_variant_id:id});setLoading(false);if(error){showToast(error.message,'error');return}setRows((data as Row[])||[])}
 const selected=variants.find(v=>v.id===variantId)
 return <div className="p-3 md:p-5 max-w-6xl mx-auto"><div className="flex items-center justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><Scale size={20} className="text-cyan-400"/><h1 className="text-xl font-bold text-white">Comparador de proveedores</h1></div><p className="text-xs text-gray-500 mt-1">Compara último costo, mínimo, promedio y volumen histórico por variante.</p></div><button onClick={()=>comparar()} className="rounded-xl border border-[#30363d] p-2.5 text-gray-400"><RefreshCw size={16}/></button></div>
 <section className="rounded-2xl border border-[#30363d] bg-[#161b22] p-4 mb-4"><label className="text-xs text-gray-500">Producto / variante</label><select value={variantId} onChange={e=>{setVariantId(e.target.value);void comparar(e.target.value)}} className="input-personal w-full mt-1"><option value="">Selecciona una variante...</option>{variants.map(v=><option key={v.id} value={v.id}>{v.product?.nombre||'Producto'}{v.color?` · ${v.color}`:''}{v.product?.sku?` · ${v.product.sku}`:''}</option>)}</select>{selected&&<p className="text-[11px] text-gray-500 mt-2">Analizando: {selected.product?.nombre}{selected.color?` / ${selected.color}`:''}</p>}</section>
 <section className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden">{loading?<p className="p-8 text-center text-sm text-gray-500">Comparando...</p>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead><tr className="border-b border-[#30363d] text-gray-500"><th className="p-3 text-left">Proveedor</th><th className="p-3 text-right">Último costo</th><th className="p-3 text-right">Mínimo</th><th className="p-3 text-right">Promedio</th><th className="p-3 text-right">Unidades</th><th className="p-3 text-right">Última compra</th></tr></thead><tbody className="divide-y divide-[#21262d]">{rows.map((r,i)=><tr key={r.proveedor_id} className={i===0?'bg-green-500/5':''}><td className="p-3 text-white font-semibold">{r.proveedor}{i===0&&<span className="ml-2 text-[10px] text-green-300">mejor promedio</span>}</td><td className="p-3 text-right text-cyan-300 font-bold">{money(r.ultimo_costo)}</td><td className="p-3 text-right text-gray-300">{money(r.costo_minimo)}</td><td className="p-3 text-right text-white">{money(r.costo_promedio)}</td><td className="p-3 text-right text-gray-300">{r.unidades_compradas}</td><td className="p-3 text-right text-gray-500">{r.ultima_compra?new Date(r.ultima_compra).toLocaleDateString('es-PE'):'—'}</td></tr>)}</tbody></table>{variantId&&!rows.length&&<p className="p-8 text-center text-xs text-gray-600">Aún no existe historial de costos para esta variante.</p>}</div>}</section></div>
}
