import { useEffect,useMemo,useState } from 'react'
import { PackagePlus,Plus,RefreshCw,X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { useToast } from '../lib/toast'

type Prov={id:string;nombre:string}
type Variant={id:string;product:{nombre:string}|null;color:string|null}
type Orden={id:string;numero:number;estado:string;total:number;fecha_orden:string;fecha_esperada:string|null;proveedor:{nombre:string}|null;location_id:string}
type Item={id:string;variant_id:string;cantidad_pedida:number;cantidad_recibida:number;costo_unitario:number;variant:{product:{nombre:string}|null;color:string|null}|null}

type LineaNueva={variant_id:string;cantidad:number;costo_unitario:number}

export default function Compras(){
 const {staff,isAdmin}=useAuth(); const puedeRecibir=isAdmin||['tecnico','encargado','jefa'].includes(staff?.puesto||''); const {showToast}=useToast(); const [ordenes,setOrdenes]=useState<Orden[]>([]); const [proveedores,setProveedores]=useState<Prov[]>([]); const [variants,setVariants]=useState<Variant[]>([]); const [openNew,setOpenNew]=useState(false); const [detalle,setDetalle]=useState<Orden|null>(null); const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);const [o,p,v]=await Promise.all([supabase.from('ordenes_compra').select('id,numero,estado,total,fecha_orden,fecha_esperada,location_id,proveedor:proveedores(nombre)').order('fecha_orden',{ascending:false}),isAdmin?supabase.from('proveedores').select('id,nombre').eq('activo',true).order('nombre'):Promise.resolve({data:[] as Prov[],error:null}),supabase.from('product_variants').select('id,color,product:products(nombre)').order('created_at',{ascending:false}).limit(500)]); if(o.error||v.error)showToast('No se pudieron cargar compras','error');setOrdenes((o.data as unknown as Orden[])||[]);setProveedores((p.data as Prov[])||[]);setVariants((v.data as unknown as Variant[])||[]);setLoading(false)}
 useEffect(()=>{load()},[isAdmin])
 const abrir=async(o:Orden)=>{setDetalle(o);const {data,error}=await supabase.from('orden_compra_items').select('id,variant_id,cantidad_pedida,cantidad_recibida,costo_unitario,variant:product_variants(color,product:products(nombre))').eq('orden_id',o.id);if(error)showToast('No se pudo cargar la orden','error');setItems((data as unknown as Item[])||[])}
 return <div className="p-3 md:p-5 max-w-7xl mx-auto"><div className="flex flex-wrap items-center justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><PackagePlus size={20} className="text-cyan-400"/><h1 className="font-display font-bold text-xl text-white">Compras</h1></div><p className="text-xs text-gray-500 mt-1">Órdenes de compra y recepción de mercadería.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-[#30363d] px-3 py-2 text-sm text-gray-300 inline-flex gap-2 items-center"><RefreshCw size={14}/>Actualizar</button>{isAdmin&&<button onClick={()=>setOpenNew(true)} className="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-black inline-flex gap-2 items-center"><Plus size={14}/>Nueva orden</button>}</div></div><div className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden">{loading?<div className="p-10 text-center text-sm text-gray-500">Cargando...</div>:<div className="divide-y divide-[#21262d]">{ordenes.map(o=><button key={o.id} onClick={()=>abrir(o)} className="w-full text-left p-4 hover:bg-[#1c2128] flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-white">OC #{o.numero} · {o.proveedor?.nombre||'Proveedor'}</p><p className="text-xs text-gray-500">{new Date(o.fecha_orden).toLocaleString('es-PE')}{o.fecha_esperada?` · esperada ${o.fecha_esperada}`:''}</p></div><div className="text-right"><p className="text-sm font-bold text-cyan-400">S/ {Number(o.total).toFixed(2)}</p><span className="text-[10px] uppercase text-gray-500">{o.estado}</span></div></button>)}{ordenes.length===0&&<div className="p-10 text-center text-sm text-gray-600">No hay órdenes de compra.</div>}</div>}</div>{openNew&&<NuevaOrden proveedores={proveedores} variants={variants} onClose={()=>setOpenNew(false)} onSaved={async()=>{setOpenNew(false);await load()}}/>}{detalle&&<Detalle orden={detalle} items={items} puedeRecibir={puedeRecibir} onClose={()=>{setDetalle(null);setItems([])}} onSaved={async()=>{await load();await abrir(detalle)}}/>}</div>
}

function NuevaOrden({proveedores,variants,onClose,onSaved}:{proveedores:Prov[];variants:Variant[];onClose:()=>void;onSaved:()=>void}){const {showToast}=useToast();const [proveedorId,setProveedorId]=useState(proveedores[0]?.id||'');const [fechaEsperada,setFechaEsperada]=useState('');const [obs,setObs]=useState('');const [lineas,setLineas]=useState<LineaNueva[]>([{variant_id:variants[0]?.id||'',cantidad:1,costo_unitario:0}]);const [saving,setSaving]=useState(false);const total=useMemo(()=>lineas.reduce((a,l)=>a+l.cantidad*l.costo_unitario,0),[lineas]);const save=async()=>{if(!proveedorId||lineas.some(l=>!l.variant_id||l.cantidad<=0||l.costo_unitario<0))return;setSaving(true);const {error}=await supabase.rpc('crear_orden_compra',{p_proveedor_id:proveedorId,p_items:lineas,p_fecha_esperada:fechaEsperada||null,p_observacion:obs||null});setSaving(false);if(error){showToast(error.message,'error');return}showToast('Orden creada','success');onSaved()};return <Modal title="Nueva orden de compra" onClose={onClose}><label className="text-xs text-gray-500">Proveedor</label><select value={proveedorId} onChange={e=>setProveedorId(e.target.value)} className="input-personal mt-1 w-full">{proveedores.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><label className="block text-xs text-gray-500 mt-3">Fecha esperada</label><input type="date" value={fechaEsperada} onChange={e=>setFechaEsperada(e.target.value)} className="input-personal mt-1 w-full"/><div className="mt-4 space-y-2">{lineas.map((l,i)=><div key={i} className="grid grid-cols-[1fr_80px_100px_32px] gap-2"><select value={l.variant_id} onChange={e=>setLineas(x=>x.map((q,j)=>j===i?{...q,variant_id:e.target.value}:q))} className="input-personal"><option value="">Producto...</option>{variants.map(v=><option key={v.id} value={v.id}>{v.product?.nombre||'Producto'}{v.color?` · ${v.color}`:''}</option>)}</select><input type="number" min={1} value={l.cantidad} onChange={e=>setLineas(x=>x.map((q,j)=>j===i?{...q,cantidad:Number(e.target.value)}:q))} className="input-personal"/><input type="number" min={0} step="0.01" value={l.costo_unitario} onChange={e=>setLineas(x=>x.map((q,j)=>j===i?{...q,costo_unitario:Number(e.target.value)}:q))} className="input-personal"/><button onClick={()=>setLineas(x=>x.filter((_,j)=>j!==i))} className="text-red-400">×</button></div>)}</div><button onClick={()=>setLineas(x=>[...x,{variant_id:'',cantidad:1,costo_unitario:0}])} className="mt-2 text-xs text-cyan-400">+ Agregar línea</button><textarea value={obs} onChange={e=>setObs(e.target.value)} placeholder="Observación" className="input-personal mt-3 w-full"/><div className="flex justify-between mt-4"><span className="text-sm text-gray-400">Total: <b className="text-white">S/ {total.toFixed(2)}</b></span><button onClick={save} disabled={saving} className="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-black disabled:opacity-40">{saving?'Guardando...':'Crear orden'}</button></div></Modal>}

function Detalle({orden,items,puedeRecibir,onClose,onSaved}:{orden:Orden;items:Item[];puedeRecibir:boolean;onClose:()=>void;onSaved:()=>void}){const {showToast}=useToast();const [qty,setQty]=useState<Record<string,number>>({});const [saving,setSaving]=useState(false);const recibir=async()=>{const payload=items.map(i=>({orden_item_id:i.id,cantidad:Math.max(0,qty[i.id]||0)})).filter(x=>x.cantidad>0);if(payload.length===0)return;setSaving(true);const {error}=await supabase.rpc('recibir_orden_compra',{p_orden_id:orden.id,p_items:payload,p_observacion:null});setSaving(false);if(error){showToast(error.message,'error');return}showToast('Recepción registrada','success');onSaved()};return <Modal title={`OC #${orden.numero}`} onClose={onClose}><div className="space-y-2">{items.map(i=>{const pend=i.cantidad_pedida-i.cantidad_recibida;return <div key={i.id} className="rounded-xl border border-[#30363d] p-3"><div className="flex justify-between gap-3"><div><p className="text-sm text-white">{i.variant?.product?.nombre||'Producto'}{i.variant?.color?` · ${i.variant.color}`:''}</p><p className="text-[11px] text-gray-500">Pedido {i.cantidad_pedida} · recibido {i.cantidad_recibida} · pendiente {pend} · S/ {Number(i.costo_unitario).toFixed(2)}</p></div>{puedeRecibir&&pend>0&&<input type="number" min={0} max={pend} value={qty[i.id]||0} onChange={e=>setQty({...qty,[i.id]:Math.min(pend,Number(e.target.value))})} className="input-personal w-20"/>}</div></div>})}</div>{puedeRecibir&&['borrador','enviada','parcial'].includes(orden.estado)&&<button onClick={recibir} disabled={saving} className="mt-4 w-full rounded-xl bg-green-500 px-4 py-2 text-sm font-bold text-black disabled:opacity-40">{saving?'Registrando...':'Registrar recepción'}</button>}</Modal>}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[70] bg-black/65 flex items-end md:items-center justify-center"><div className="w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-t-2xl md:rounded-2xl border border-[#30363d] bg-[#161b22] p-5 relative"><button onClick={onClose} className="absolute right-4 top-4 text-gray-500"><X size={18}/></button><h3 className="font-bold text-white mb-4">{title}</h3>{children}</div></div>}
