import { useEffect, useMemo, useState } from 'react'
import { BadgeCheck, RefreshCw, AlertTriangle, XCircle } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useToast } from '../lib/toast'

type Row={id:string;payment_id:string;sale_id:string;metodo:string;monto_esperado:number;monto_confirmado:number|null;referencia_venta:string|null;referencia_proveedor:string|null;proveedor:string|null;estado:string;created_at:string;sale:{numero:number}|null}
type Summary={fecha:string;pendientes:number;conciliados:number;diferencias:number;rechazados:number;monto_pendiente:number;monto_diferencia:number}
const money=(v:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v||0))

export default function ConciliacionPagos(){
 const {showToast}=useToast();const hoy=new Date().toISOString().slice(0,10);const [fecha,setFecha]=useState(hoy);const [rows,setRows]=useState<Row[]>([]);const [summary,setSummary]=useState<Summary|null>(null);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<Row|null>(null)
 const load=async()=>{setLoading(true);await supabase.rpc('sincronizar_conciliaciones_pago_admin',{});const start=`${fecha}T00:00:00-05:00`,end=new Date(`${fecha}T00:00:00-05:00`);end.setDate(end.getDate()+1);const [r,s]=await Promise.all([supabase.from('conciliaciones_pago').select('id,payment_id,sale_id,metodo,monto_esperado,monto_confirmado,referencia_venta,referencia_proveedor,proveedor,estado,created_at,sale:sales(numero)').gte('created_at',start).lt('created_at',end.toISOString()).order('created_at',{ascending:false}),supabase.rpc('resumen_conciliacion_pagos_admin',{p_fecha:fecha})]);if(r.error||s.error)showToast('No se pudo cargar la conciliación','error');setRows((r.data as unknown as Row[])||[]);setSummary((s.data as Summary)||null);setLoading(false)}
 useEffect(()=>{load()},[fecha])
 const pendientes=useMemo(()=>rows.filter(r=>r.estado!=='conciliado'),[rows])
 return <div className="p-3 md:p-5 max-w-7xl mx-auto"><div className="flex flex-wrap items-center justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><BadgeCheck size={20} className="text-cyan-400"/><h1 className="text-xl font-bold text-white">Conciliación de pagos</h1></div><p className="text-xs text-gray-500 mt-1">Compara pagos no efectivos con la confirmación del proveedor/POS.</p></div><button onClick={load} className="rounded-xl border border-[#30363d] p-2.5 text-gray-400"><RefreshCw size={16}/></button></div>
 <div className="mb-4"><input type="date" value={fecha} onChange={e=>setFecha(e.target.value)} className="rounded-xl border border-[#30363d] bg-[#161b22] px-3 py-2 text-sm text-white"/></div>
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-5"><Metric label="Pendientes" value={String(summary?.pendientes||0)} sub={money(summary?.monto_pendiente||0)}/><Metric label="Conciliados" value={String(summary?.conciliados||0)}/><Metric label="Diferencias" value={String(summary?.diferencias||0)} sub={money(summary?.monto_diferencia||0)}/><Metric label="Rechazados" value={String(summary?.rechazados||0)}/><Metric label="Por revisar" value={String(pendientes.length)}/></div>
 <section className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden">{loading?<p className="p-8 text-center text-sm text-gray-500">Sincronizando...</p>:<div className="divide-y divide-[#21262d]">{rows.map(r=><div key={r.id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold text-white">Venta #{r.sale?.numero||'—'} · {r.metodo.toUpperCase()}</p><Estado estado={r.estado}/></div><p className="text-[11px] text-gray-500 mt-1">Esperado {money(r.monto_esperado)}{r.referencia_venta?` · ref. venta ${r.referencia_venta}`:''}{r.referencia_proveedor?` · ref. proveedor ${r.referencia_proveedor}`:''}</p></div><div className="flex items-center gap-3"><p className="font-bold text-cyan-300">{money(r.monto_confirmado??r.monto_esperado)}</p>{r.estado!=='conciliado'&&<button onClick={()=>setSelected(r)} className="rounded-lg border border-[#30363d] px-3 py-2 text-xs text-gray-300">Revisar</button>}</div></div>)}{!rows.length&&<p className="p-8 text-center text-xs text-gray-600">No hay pagos no efectivos para esta fecha.</p>}</div>}</section>{selected&&<Resolver row={selected} onClose={()=>setSelected(null)} onSaved={async()=>{setSelected(null);await load()}}/>}</div>
}
function Resolver({row,onClose,onSaved}:{row:Row;onClose:()=>void;onSaved:()=>void}){const {showToast}=useToast();const [monto,setMonto]=useState(String(row.monto_esperado));const [ref,setRef]=useState(row.referencia_proveedor||'');const [obs,setObs]=useState('');const run=async(estado:'conciliado'|'diferencia'|'rechazado')=>{const {error}=await supabase.rpc('conciliar_pago_admin',{p_payment_id:row.payment_id,p_estado:estado,p_monto_confirmado:Number(monto),p_referencia_proveedor:ref||null,p_observacion:obs||null});if(error){showToast(error.message,'error');return}showToast('Conciliación actualizada','success');onSaved()};return <div className="fixed inset-0 z-50 bg-black/60 flex items-end md:items-center justify-center"><div className="w-full max-w-md bg-[#161b22] border border-[#30363d] rounded-t-2xl md:rounded-2xl p-5 space-y-3"><div className="flex justify-between"><h3 className="font-bold text-white">Revisar pago</h3><button onClick={onClose} className="text-gray-500">×</button></div><label className="block"><span className="text-xs text-gray-500">Monto confirmado</span><input type="number" step="0.01" value={monto} onChange={e=>setMonto(e.target.value)} className="input-personal w-full mt-1"/></label><label className="block"><span className="text-xs text-gray-500">Referencia proveedor/POS</span><input value={ref} onChange={e=>setRef(e.target.value)} className="input-personal w-full mt-1"/></label><textarea value={obs} onChange={e=>setObs(e.target.value)} placeholder="Observación" className="input-personal w-full"/><div className="grid grid-cols-3 gap-2"><button onClick={()=>run('conciliado')} className="rounded-xl bg-green-500/15 text-green-300 py-2 text-xs font-bold">Conciliar</button><button onClick={()=>run('diferencia')} className="rounded-xl bg-orange-500/15 text-orange-300 py-2 text-xs font-bold">Diferencia</button><button onClick={()=>run('rechazado')} className="rounded-xl bg-red-500/15 text-red-300 py-2 text-xs font-bold">Rechazar</button></div></div></div>}
function Estado({estado}:{estado:string}){const cls=estado==='conciliado'?'text-green-300 bg-green-500/10':estado==='diferencia'?'text-orange-300 bg-orange-500/10':estado==='rechazado'?'text-red-300 bg-red-500/10':'text-yellow-300 bg-yellow-500/10';const Icon=estado==='conciliado'?BadgeCheck:estado==='rechazado'?XCircle:AlertTriangle;return <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] ${cls}`}><Icon size={10}/>{estado}</span>}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-2xl border border-[#30363d] bg-[#161b22] p-4"><p className="text-[11px] text-gray-500">{label}</p><p className="text-xl font-bold text-white mt-1">{value}</p>{sub&&<p className="text-[10px] text-gray-600 mt-1">{sub}</p>}</div>}
