import { useEffect,useState } from 'react'
import { CalendarClock,FileText,Upload,RefreshCw,X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { useToast } from '../lib/toast'

type Solicitud={id:string;tipo:string;fecha_desde:string;fecha_hasta:string;turno_id:string|null;motivo:string;documento_path:string|null;estado:string;resolucion_motivo:string|null;created_at:string;resolved_at:string|null}
type Documento={id:string;tipo:string;nombre:string;storage_path:string;mime_type:string|null;size_bytes:number|null;vence_el:string|null;observacion:string|null;created_at:string}
type Turno={id:string;nombre:string;hora_inicio:string;hora_fin:string}
const fmt=(v:string)=>new Date(`${v}T12:00:00`).toLocaleDateString('es-PE')
const badge=(e:string)=>e==='aprobada'?'text-green-400 bg-green-500/10 border-green-500/20':e==='rechazada'?'text-red-400 bg-red-500/10 border-red-500/20':e==='cancelada'?'text-gray-500 bg-gray-500/10 border-gray-500/20':'text-amber-300 bg-amber-500/10 border-amber-500/20'

export default function MisSolicitudes(){
 const {staff}=useAuth(); const {showToast}=useToast();
 const [rows,setRows]=useState<Solicitud[]>([]),[docs,setDocs]=useState<Documento[]>([]),[turnos,setTurnos]=useState<Turno[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false)
 const [tipo,setTipo]=useState('permiso'),[desde,setDesde]=useState(new Date().toISOString().slice(0,10)),[hasta,setHasta]=useState(new Date().toISOString().slice(0,10)),[turno,setTurno]=useState(''),[motivo,setMotivo]=useState(''),[file,setFile]=useState<File|null>(null),[sending,setSending]=useState(false)
 const load=async()=>{setLoading(true);const [s,d,t]=await Promise.all([supabase.rpc('mis_solicitudes_personal',{p_limit:100}),supabase.rpc('documentos_personal',{p_staff_id:null}),supabase.from('turnos').select('id,nombre,hora_inicio,hora_fin').eq('activo',true).order('hora_inicio')]);setLoading(false);if(s.error||d.error||t.error)showToast('No se pudo cargar autoservicio','error');setRows((s.data as Solicitud[])||[]);setDocs((d.data as Documento[])||[]);setTurnos((t.data as Turno[])||[])}
 useEffect(()=>{load()},[])
 const subir=async(f:File,prefix='solicitudes')=>{if(!staff?.id)throw new Error('Sin personal');const safe=f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${staff.id}/${prefix}/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('personal-documentos').upload(path,f,{upsert:false,contentType:f.type});if(error)throw error;return path}
 const crear=async()=>{if(!motivo.trim()||!staff?.id)return;setSending(true);let path:string|null=null;try{if(file)path=await subir(file);const {error}=await supabase.rpc('crear_solicitud_personal',{p_tipo:tipo,p_fecha_desde:desde,p_fecha_hasta:tipo==='cambio_turno'?desde:hasta,p_motivo:motivo.trim(),p_turno_id:tipo==='cambio_turno'?(turno||null):null,p_documento_path:path});if(error)throw error;showToast('Solicitud enviada','success');setOpen(false);setMotivo('');setFile(null);await load()}catch(e){if(path)await supabase.storage.from('personal-documentos').remove([path]);showToast(e instanceof Error?e.message:'No se pudo crear la solicitud','error')}finally{setSending(false)}}
 const cancelar=async(id:string)=>{const {data,error}=await supabase.rpc('cancelar_mi_solicitud_personal',{p_id:id});if(error||!data){showToast('No se pudo cancelar','error');return}showToast('Solicitud cancelada','success');load()}
 const abrir=async(path:string)=>{const {data,error}=await supabase.storage.from('personal-documentos').createSignedUrl(path,120);if(error||!data){showToast('No se pudo abrir el documento','error');return}window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 const subirDocumento=async(f:File)=>{if(!staff?.id)return;try{const path=await subir(f,'documentos');const {error}=await supabase.rpc('registrar_documento_personal',{p_staff_id:staff.id,p_tipo:'otro',p_nombre:f.name,p_storage_path:path,p_mime_type:f.type||null,p_size_bytes:f.size,p_vence_el:null,p_observacion:null});if(error){await supabase.storage.from('personal-documentos').remove([path]);throw error}showToast('Documento guardado','success');load()}catch(e){showToast(e instanceof Error?e.message:'No se pudo subir','error')}}
 return <div className="p-3 md:p-5 max-w-6xl mx-auto space-y-5">
  <div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarClock size={20} className="text-cyan-400"/><h1 className="text-xl font-bold text-white">Mis solicitudes</h1></div><p className="text-xs text-gray-500 mt-1">Permisos, vacaciones, licencias, cambios de turno y documentos personales.</p></div><div className="flex gap-2"><button onClick={load} className="btn-secondary"><RefreshCw size={15}/></button><button onClick={()=>setOpen(true)} className="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-black">Nueva solicitud</button></div></div>
  <section className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden"><div className="px-4 py-3 border-b border-[#30363d]"><h2 className="text-sm font-bold text-white">Solicitudes</h2></div>{loading?<p className="p-8 text-center text-gray-500 text-sm">Cargando...</p>:rows.length===0?<p className="p-8 text-center text-gray-600 text-sm">Todavía no tienes solicitudes.</p>:<div className="divide-y divide-[#21262d]">{rows.map(r=><div key={r.id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-white capitalize">{r.tipo.replace('_',' ')}</p><span className={`text-[10px] px-2 py-0.5 rounded-full border ${badge(r.estado)}`}>{r.estado}</span></div><p className="text-xs text-gray-500 mt-1">{fmt(r.fecha_desde)}{r.fecha_hasta!==r.fecha_desde?` → ${fmt(r.fecha_hasta)}`:''}</p><p className="text-xs text-gray-300 mt-1">{r.motivo}</p>{r.resolucion_motivo&&<p className="text-[11px] text-gray-500 mt-1">Respuesta: {r.resolucion_motivo}</p>}</div><div className="flex gap-2">{r.documento_path&&<button onClick={()=>abrir(r.documento_path!)} className="text-xs text-cyan-400">Ver sustento</button>}{r.estado==='pendiente'&&<button onClick={()=>cancelar(r.id)} className="text-xs text-red-400">Cancelar</button>}</div></div>)}</div>}</section>
  <section className="rounded-2xl border border-[#30363d] bg-[#161b22] p-4"><div className="flex items-center justify-between gap-3 mb-3"><div className="flex gap-2 items-center"><FileText size={16} className="text-cyan-400"/><h2 className="text-sm font-bold text-white">Mis documentos</h2></div><label className="cursor-pointer inline-flex items-center gap-2 rounded-lg border border-[#30363d] px-3 py-2 text-xs text-gray-300"><Upload size={14}/>Subir<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)subirDocumento(f);e.currentTarget.value=''}}/></label></div><div className="space-y-2">{docs.map(d=><button key={d.id} onClick={()=>abrir(d.storage_path)} className="w-full text-left rounded-xl border border-[#21262d] bg-[#0d1117] px-3 py-2"><p className="text-sm text-white">{d.nombre}</p><p className="text-[10px] text-gray-600">{d.tipo} · {new Date(d.created_at).toLocaleDateString('es-PE')}</p></button>)}{!docs.length&&<p className="text-xs text-gray-600">Sin documentos.</p>}</div></section>
  {open&&<div className="fixed inset-0 z-[70] bg-black/65 backdrop-blur-sm flex items-end md:items-center justify-center"><div className="relative w-full max-w-lg rounded-t-2xl md:rounded-2xl border border-[#30363d] bg-[#161b22] p-5"><button onClick={()=>setOpen(false)} className="absolute top-4 right-4 text-gray-500"><X size={19}/></button><h3 className="font-bold text-white mb-4">Nueva solicitud</h3><div className="grid md:grid-cols-2 gap-3"><div><label className="text-xs text-gray-500">Tipo</label><select value={tipo} onChange={e=>setTipo(e.target.value)} className="input-personal w-full mt-1"><option value="permiso">Permiso</option><option value="vacaciones">Vacaciones</option><option value="licencia">Licencia</option><option value="cambio_turno">Cambio de turno</option></select></div><div><label className="text-xs text-gray-500">Desde</label><input type="date" value={desde} onChange={e=>{setDesde(e.target.value);if(tipo==='cambio_turno')setHasta(e.target.value)}} className="input-personal w-full mt-1"/></div>{tipo!=='cambio_turno'&&<div><label className="text-xs text-gray-500">Hasta</label><input type="date" value={hasta} min={desde} onChange={e=>setHasta(e.target.value)} className="input-personal w-full mt-1"/></div>}{tipo==='cambio_turno'&&<div><label className="text-xs text-gray-500">Turno solicitado</label><select value={turno} onChange={e=>setTurno(e.target.value)} className="input-personal w-full mt-1"><option value="">Descanso excepcional</option>{turnos.map(t=><option key={t.id} value={t.id}>{t.nombre} · {t.hora_inicio.slice(0,5)}–{t.hora_fin.slice(0,5)}</option>)}</select></div>}</div><label className="block text-xs text-gray-500 mt-3">Motivo</label><textarea rows={3} value={motivo} onChange={e=>setMotivo(e.target.value)} className="input-personal w-full mt-1"/><label className="block text-xs text-gray-500 mt-3">Sustento opcional</label><input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-1 text-xs text-gray-400"/><button disabled={sending||motivo.trim().length<3} onClick={crear} className="mt-5 w-full rounded-xl bg-cyan-500 py-2.5 text-sm font-bold text-black disabled:opacity-40">{sending?'Enviando...':'Enviar solicitud'}</button></div></div>}
 </div>
}
