import { useEffect,useMemo,useState } from 'react'
import { Bell,CheckCheck,RefreshCw,AlertTriangle } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { useToast } from '../lib/toast'

type N={id:string;tipo:string;titulo:string;mensaje:string;prioridad:'baja'|'media'|'alta'|'critica';leida_at:string|null;created_at:string}
const badge=(p:N['prioridad'])=>p==='critica'?'bg-red-500/15 text-red-400 border-red-500/30':p==='alta'?'bg-orange-500/15 text-orange-400 border-orange-500/30':p==='media'?'bg-cyan-500/10 text-cyan-300 border-cyan-500/20':'bg-gray-500/10 text-gray-400 border-gray-500/20'
export default function Notificaciones(){
  const {isAdmin}=useAuth();const {showToast}=useToast();const [rows,setRows]=useState<N[]>([]),[onlyUnread,setOnlyUnread]=useState(false),[loading,setLoading]=useState(false)
  const load=async()=>{setLoading(true);const {data,error}=await supabase.rpc('notificaciones_mias',{p_limit:100});setLoading(false);if(error){showToast(error.message,'error');return}setRows((data as N[])||[])}
  useEffect(()=>{void load()},[])
  const visible=useMemo(()=>onlyUnread?rows.filter(r=>!r.leida_at):rows,[rows,onlyUnread]);const unread=rows.filter(r=>!r.leida_at).length
  const toggle=async(n:N)=>{const {error}=await supabase.rpc('marcar_notificacion_leida',{p_id:n.id,p_leida:!n.leida_at});if(error){showToast(error.message,'error');return}setRows(rs=>rs.map(r=>r.id===n.id?{...r,leida_at:n.leida_at?null:new Date().toISOString()}:r))}
  const markAll=async()=>{for(const n of rows.filter(r=>!r.leida_at)){const {error}=await supabase.rpc('marcar_notificacion_leida',{p_id:n.id,p_leida:true});if(error){showToast(error.message,'error');return}}await load();showToast('Notificaciones marcadas como leídas','success')}
  const generate=async()=>{const {data,error}=await supabase.rpc('generar_alertas_operativas_admin');if(error){showToast(error.message,'error');return}showToast(`${Number(data||0)} alerta(s) nueva(s) generada(s)`,'success');await load()}
  return <div className="p-4 md:p-6 max-w-4xl mx-auto"><div className="flex flex-wrap items-start justify-between gap-3 mb-5"><div className="flex gap-3"><div className="w-10 h-10 rounded-xl bg-cyan-500/15 text-cyan-400 flex items-center justify-center"><Bell size={21}/></div><div><h1 className="text-xl font-bold text-white">Notificaciones</h1><p className="text-xs text-gray-500">{unread} sin leer · alertas operativas y personales</p></div></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-lg border border-[#30363d] p-2 text-gray-400 hover:text-white"><RefreshCw size={16} className={loading?'animate-spin':''}/></button>{unread>0&&<button onClick={()=>void markAll()} className="rounded-lg border border-[#30363d] px-3 py-2 text-xs text-gray-300 flex items-center gap-2"><CheckCheck size={15}/>Leer todas</button>}{isAdmin&&<button onClick={()=>void generate()} className="rounded-lg bg-cyan-500 px-3 py-2 text-xs font-bold text-black">Generar alertas</button>}</div></div><div className="mb-3 flex gap-2"><button onClick={()=>setOnlyUnread(false)} className={`rounded-full px-3 py-1.5 text-xs ${!onlyUnread?'bg-cyan-500 text-black font-bold':'bg-[#161b22] text-gray-400 border border-[#30363d]'}`}>Todas</button><button onClick={()=>setOnlyUnread(true)} className={`rounded-full px-3 py-1.5 text-xs ${onlyUnread?'bg-cyan-500 text-black font-bold':'bg-[#161b22] text-gray-400 border border-[#30363d]'}`}>Sin leer ({unread})</button></div><div className="space-y-2">{visible.map(n=><button key={n.id} onClick={()=>void toggle(n)} className={`w-full text-left rounded-xl border p-4 transition ${n.leida_at?'border-[#21262d] bg-[#0d1117] opacity-65':'border-[#30363d] bg-[#161b22] hover:border-cyan-500/30'}`}><div className="flex justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`rounded-full border px-2 py-0.5 text-[9px] font-bold uppercase ${badge(n.prioridad)}`}>{n.prioridad}</span><p className="text-sm font-bold text-white truncate">{n.titulo}</p>{!n.leida_at&&<span className="w-2 h-2 rounded-full bg-cyan-400 shrink-0"/>}</div><p className="mt-2 text-xs leading-relaxed text-gray-400">{n.mensaje}</p></div><span className="shrink-0 text-[10px] text-gray-600">{new Date(n.created_at).toLocaleString('es-PE')}</span></div></button>)}{!loading&&!visible.length&&<div className="rounded-xl border border-[#30363d] bg-[#161b22] p-10 text-center"><AlertTriangle size={24} className="mx-auto text-gray-600 mb-2"/><p className="text-sm text-gray-500">No hay notificaciones en este filtro.</p></div>}</div></div>
}
