import { useEffect, useState } from 'react'
import { Building2, Plus, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useToast } from '../lib/toast'

type Proveedor={id:string;nombre:string;ruc:string|null;telefono:string|null;email:string|null;contacto:string|null;activo:boolean}

export default function Proveedores(){
 const {showToast}=useToast(); const [rows,setRows]=useState<Proveedor[]>([]); const [open,setOpen]=useState(false)
 const load=async()=>{const {data,error}=await supabase.from('proveedores').select('id,nombre,ruc,telefono,email,contacto,activo').order('nombre'); if(error)showToast('No se pudieron cargar proveedores','error'); setRows(data||[])}
 useEffect(()=>{load()},[])
 return <div className="p-3 md:p-5 max-w-6xl mx-auto"><div className="flex items-center justify-between mb-5"><div><div className="flex items-center gap-2"><Building2 className="text-cyan-400" size={20}/><h1 className="font-display font-bold text-xl text-white">Proveedores</h1></div><p className="text-xs text-gray-500 mt-1">Maestro de proveedores para órdenes de compra y abastecimiento.</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-black"><Plus size={15}/> Nuevo proveedor</button></div><div className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden"><div className="divide-y divide-[#21262d]">{rows.map(r=><div key={r.id} className="p-4 flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-white">{r.nombre}</p><p className="text-xs text-gray-500">{r.ruc?`RUC ${r.ruc}`:'Sin RUC'}{r.contacto?` · ${r.contacto}`:''}</p><p className="text-[11px] text-gray-600">{r.telefono||''}{r.email?` · ${r.email}`:''}</p></div><span className={`text-[10px] px-2 py-1 rounded-full ${r.activo?'bg-green-500/10 text-green-400':'bg-gray-500/10 text-gray-500'}`}>{r.activo?'Activo':'Inactivo'}</span></div>)}{rows.length===0&&<div className="p-10 text-center text-sm text-gray-600">No hay proveedores registrados.</div>}</div></div>{open&&<Modal onClose={()=>setOpen(false)} onSaved={async()=>{setOpen(false);await load()}}/>}</div>
}

function Modal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const {showToast}=useToast(); const [f,setF]=useState({nombre:'',ruc:'',telefono:'',email:'',direccion:'',contacto:'',notas:''}); const [saving,setSaving]=useState(false); const save=async()=>{if(f.nombre.trim().length<2)return;setSaving(true);const {error}=await supabase.rpc('crear_proveedor',{p_nombre:f.nombre,p_ruc:f.ruc||null,p_telefono:f.telefono||null,p_email:f.email||null,p_direccion:f.direccion||null,p_contacto:f.contacto||null,p_notas:f.notas||null});setSaving(false);if(error){showToast(error.message,'error');return}showToast('Proveedor creado','success');onSaved()};return <div className="fixed inset-0 z-[70] bg-black/65 flex items-end md:items-center justify-center"><div className="w-full max-w-lg rounded-t-2xl md:rounded-2xl border border-[#30363d] bg-[#161b22] p-5 relative"><button onClick={onClose} className="absolute right-4 top-4 text-gray-500"><X size={18}/></button><h3 className="font-bold text-white mb-4">Nuevo proveedor</h3><div className="grid md:grid-cols-2 gap-3">{(['nombre','ruc','telefono','email','contacto','direccion'] as const).map(k=><div key={k}><label className="text-xs text-gray-500 capitalize">{k}</label><input value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} className="mt-1 w-full rounded-xl border border-[#30363d] bg-[#0d1117] px-3 py-2 text-sm text-white"/></div>)}</div><label className="block text-xs text-gray-500 mt-3">Notas</label><textarea value={f.notas} onChange={e=>setF({...f,notas:e.target.value})} className="mt-1 w-full rounded-xl border border-[#30363d] bg-[#0d1117] px-3 py-2 text-sm text-white"/><div className="flex gap-2 mt-4"><button onClick={onClose} className="flex-1 rounded-xl border border-[#30363d] py-2 text-sm text-gray-300">Cancelar</button><button onClick={save} disabled={saving||f.nombre.trim().length<2} className="flex-1 rounded-xl bg-cyan-500 py-2 text-sm font-bold text-black disabled:opacity-40">{saving?'Guardando...':'Guardar'}</button></div></div></div>}
