import { useEffect,useMemo,useState } from 'react'
import { Barcode,Plus,X,ShoppingCart } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { useToast } from '../lib/toast'

type Product={id:string;nombre:string;sku:string|null;control_serial:boolean}
type Variant={id:string;product_id:string;color:string|null;product:{nombre:string;control_serial:boolean}|null}
type Serial={id:string;variant_id:string;serial_number:string;imei2:string|null;estado:string;location_id:string;variant:{color:string|null;product:{nombre:string}|null}|null}
type Reservation={variant_id:string;serial_id:string}

export default function Seriales(){
 const {isAdmin,staff}=useAuth(); const {showToast}=useToast();
 const [products,setProducts]=useState<Product[]>([]),[variants,setVariants]=useState<Variant[]>([]),[serials,setSerials]=useState<Serial[]>([]),[reservations,setReservations]=useState<Reservation[]>([])
 const [q,setQ]=useState(''),[open,setOpen]=useState(false)
 const puedeRegistrar=isAdmin||['tecnico','encargado','jefa'].includes(staff?.puesto||'')
 const load=async()=>{const [p,v,s,r]=await Promise.all([supabase.from('products').select('id,nombre,sku,control_serial').eq('activo',true).order('nombre'),supabase.from('product_variants').select('id,product_id,color,product:products(nombre,control_serial)').order('created_at',{ascending:false}).limit(500),supabase.from('product_serials').select('id,variant_id,serial_number,imei2,estado,location_id,variant:product_variants(color,product:products(nombre))').order('created_at',{ascending:false}).limit(1000),supabase.from('serial_reservations').select('variant_id,serial_id')]);if(p.error||v.error||s.error||r.error)showToast('No se pudieron cargar seriales','error');setProducts((p.data as Product[])||[]);setVariants((v.data as unknown as Variant[])||[]);setSerials((s.data as unknown as Serial[])||[]);setReservations((r.data as Reservation[])||[])}
 useEffect(()=>{load()},[])
 const reservedIds=useMemo(()=>new Set(reservations.map(r=>r.serial_id)),[reservations])
 const filtered=useMemo(()=>serials.filter(s=>`${s.serial_number} ${s.imei2||''} ${s.variant?.product?.nombre||''}`.toLowerCase().includes(q.toLowerCase())),[serials,q])
 const toggle=async(p:Product)=>{const {error}=await supabase.rpc('configurar_control_serial',{p_product_id:p.id,p_activo:!p.control_serial});if(error){showToast(error.message,'error');return}showToast(!p.control_serial?'Control serial activado':'Control serial desactivado','success');await load()}
 const reservar=async(s:Serial)=>{const actuales=reservations.filter(r=>r.variant_id===s.variant_id).map(r=>r.serial_id);const next=reservedIds.has(s.id)?actuales.filter(id=>id!==s.id):[...actuales,s.id];const {error}=await supabase.rpc('reservar_seriales_carrito',{p_variant_id:s.variant_id,p_serial_ids:next});if(error){showToast(error.message,'error');return}showToast(reservedIds.has(s.id)?'Serial liberado':'Serial reservado para venta','success');await load()}
 return <div className="p-3 md:p-5 max-w-7xl mx-auto"><div className="flex flex-wrap justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><Barcode size={20} className="text-cyan-400"/><h1 className="text-xl font-bold text-white">IMEI y seriales</h1></div><p className="text-xs text-gray-500 mt-1">Reserva aquí las unidades que venderás; el POS las consume automáticamente al cobrar.</p></div>{puedeRegistrar&&<button onClick={()=>setOpen(true)} className="rounded-xl bg-cyan-500 px-4 py-2 text-sm font-bold text-black inline-flex gap-2 items-center"><Plus size={15}/>Registrar seriales</button>}</div>
 {reservations.length>0&&<div className="mb-4 rounded-2xl border border-orange-500/30 bg-orange-500/10 p-4"><p className="text-sm font-bold text-orange-300 flex gap-2 items-center"><ShoppingCart size={15}/>{reservations.length} unidad(es) reservada(s) para tu próxima venta</p><p className="text-[11px] text-orange-200/60 mt-1">La cantidad reservada por producto debe coincidir con la cantidad del carrito. Las reservas expiran en 30 minutos.</p></div>}
 {isAdmin&&<div className="rounded-2xl border border-[#30363d] bg-[#161b22] p-4 mb-4"><h2 className="text-sm font-bold text-white mb-3">Control por producto</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-2 max-h-56 overflow-y-auto">{products.map(p=><button key={p.id} onClick={()=>toggle(p)} className={`text-left rounded-xl border px-3 py-2 ${p.control_serial?'border-cyan-500/30 bg-cyan-500/10':'border-[#30363d] bg-[#0d1117]'}`}><p className="text-xs font-semibold text-white truncate">{p.nombre}</p><p className={`text-[10px] ${p.control_serial?'text-cyan-400':'text-gray-600'}`}>{p.control_serial?'Serial obligatorio':'Sin control serial'}</p></button>)}</div></div>}
 <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar IMEI, serie o producto..." className="input-personal w-full mb-3"/><div className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden"><div className="divide-y divide-[#21262d]">{filtered.map(s=>{const reserved=reservedIds.has(s.id);return <div key={s.id} className="p-3 flex justify-between gap-3"><div><p className="text-sm text-white">{s.variant?.product?.nombre||'Producto'}{s.variant?.color?` · ${s.variant.color}`:''}</p><p className="text-xs font-mono text-cyan-300">{s.serial_number}</p>{s.imei2&&<p className="text-[10px] font-mono text-gray-500">IMEI2 {s.imei2}</p>}</div><div className="text-right"><span className={`text-[10px] uppercase ${s.estado==='disponible'?'text-green-400':s.estado==='vendido'?'text-gray-500':s.estado==='en_transito'?'text-orange-400':'text-cyan-400'}`}>{s.estado}</span>{s.estado==='disponible'&&<button onClick={()=>reservar(s)} className={`block mt-2 rounded-lg border px-3 py-1.5 text-xs ${reserved?'border-orange-500/30 bg-orange-500/10 text-orange-300':'border-cyan-500/30 text-cyan-300'}`}>{reserved?'Liberar':'Reservar venta'}</button>}</div></div>})}{filtered.length===0&&<div className="p-10 text-center text-sm text-gray-600">No hay seriales que coincidan.</div>}</div></div>{open&&<Modal variants={variants.filter(v=>v.product?.control_serial)} onClose={()=>setOpen(false)} onSaved={async()=>{setOpen(false);await load()}}/>}</div>
}
function Modal({variants,onClose,onSaved}:{variants:Variant[];onClose:()=>void;onSaved:()=>void}){const {showToast}=useToast();const [variantId,setVariantId]=useState(variants[0]?.id||'');const [text,setText]=useState('');const save=async()=>{const lines=text.split(/\n|,/).map(x=>x.trim()).filter(Boolean);const seriales=lines.map(x=>{const [serial_number,imei2]=x.split('|').map(y=>y.trim());return{serial_number,imei2:imei2||null}});if(!variantId||seriales.length===0)return;const {error}=await supabase.rpc('registrar_seriales',{p_variant_id:variantId,p_seriales:seriales});if(error){showToast(error.message,'error');return}showToast(`${seriales.length} serial(es) registrados`,'success');onSaved()};return <div className="fixed inset-0 z-[70] bg-black/65 flex items-end md:items-center justify-center"><div className="w-full max-w-lg rounded-t-2xl md:rounded-2xl border border-[#30363d] bg-[#161b22] p-5 relative"><button onClick={onClose} className="absolute right-4 top-4 text-gray-500"><X size={18}/></button><h3 className="font-bold text-white mb-4">Registrar seriales</h3><select value={variantId} onChange={e=>setVariantId(e.target.value)} className="input-personal w-full"><option value="">Producto...</option>{variants.map(v=><option key={v.id} value={v.id}>{v.product?.nombre||'Producto'}{v.color?` · ${v.color}`:''}</option>)}</select><p className="text-[10px] text-gray-600 mt-3">Una unidad por línea. Formato opcional para segundo IMEI: <code>SERIAL|IMEI2</code>.</p><textarea value={text} onChange={e=>setText(e.target.value)} rows={8} placeholder={'IMEI-001\nIMEI-002|IMEI2-002'} className="input-personal w-full mt-2 font-mono"/><button onClick={save} className="mt-4 w-full rounded-xl bg-cyan-500 py-2.5 text-sm font-bold text-black">Registrar</button></div></div>}
