import { useEffect, useMemo, useState } from 'react'
import { Boxes, RefreshCw, History, ScanLine, AlertTriangle } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useToast } from '../lib/toast'

type Row={location_id:string;variant_id:string;producto:string;sku:string|null;color:string|null;cantidad:number;costo_unitario:number;valor_stock:number}
type Hist={id:string;product_id:string;costo_anterior:number|null;costo_nuevo:number;origen:string;created_at:string;product:{nombre:string}|null}
type SerialDiff={variant_id:string;producto:string;color:string|null;stock_numerico:number;seriales_disponibles:number;diferencia:number}
const money=(v:number)=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v||0))

export default function ValorizacionInventario(){
 const {showToast}=useToast(); const [rows,setRows]=useState<Row[]>([]); const [hist,setHist]=useState<Hist[]>([]); const [serialDiffs,setSerialDiffs]=useState<SerialDiff[]>([]); const [loading,setLoading]=useState(true); const [fixing,setFixing]=useState<string|null>(null)
 const load=async()=>{setLoading(true);const [r,h,s]=await Promise.all([supabase.rpc('inventario_valorizado_admin',{p_location_id:null}),supabase.from('product_cost_history').select('id,product_id,costo_anterior,costo_nuevo,origen,created_at,product:products(nombre)').order('created_at',{ascending:false}).limit(50),supabase.rpc('reconciliacion_seriales_admin',{p_location_id:null})]);if(r.error||h.error||s.error)showToast('No se pudo cargar la valorización','error');setRows((r.data as Row[])||[]);setHist((h.data as unknown as Hist[])||[]);setSerialDiffs((s.data as SerialDiff[])||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const reconciliar=async(r:SerialDiff)=>{if(r.diferencia===0)return;if(!window.confirm(`¿Ajustar el stock numérico de ${r.producto} ${r.color||''} para que coincida con ${r.seriales_disponibles} unidades serializadas disponibles?`))return;setFixing(r.variant_id);const {data,error}=await supabase.rpc('ajustar_stock_a_seriales_admin',{p_variant_id:r.variant_id,p_motivo:'Reconciliación IMEI/serial desde Valorización'});setFixing(null);if(error){showToast(error.message,'error');return}showToast(`Stock reconciliado. Diferencia aplicada: ${Number(data||0)}`,'success');await load()}
 const total=useMemo(()=>rows.reduce((a,r)=>a+Number(r.valor_stock||0),0),[rows]); const units=useMemo(()=>rows.reduce((a,r)=>a+Number(r.cantidad||0),0),[rows]); const discrepancias=useMemo(()=>serialDiffs.filter(x=>x.diferencia!==0),[serialDiffs])
 return <div className="p-3 md:p-5 max-w-7xl mx-auto"><div className="flex items-center justify-between gap-3 mb-5"><div><div className="flex items-center gap-2"><Boxes size={20} className="text-cyan-400"/><h1 className="text-xl font-bold text-white">Valorización de inventario</h1></div><p className="text-xs text-gray-500 mt-1">Valor contable, historial de costos y consistencia entre stock e IMEI/seriales.</p></div><button onClick={load} className="rounded-xl border border-[#30363d] p-2.5 text-gray-400"><RefreshCw size={16}/></button></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><Metric label="Valor del stock" value={money(total)}/><Metric label="Unidades" value={String(units)}/><Metric label="SKUs valorizados" value={String(rows.length)}/><Metric label="Discrepancias IMEI" value={String(discrepancias.length)}/></div>
 {discrepancias.length>0&&<section className="rounded-2xl border border-orange-500/20 bg-orange-500/5 overflow-hidden mb-4"><div className="p-4 border-b border-orange-500/20 flex items-center gap-2"><AlertTriangle size={16} className="text-orange-300"/><h2 className="text-sm font-bold text-white">Reconciliación IMEI / stock</h2></div><div className="divide-y divide-orange-500/10">{discrepancias.map(r=><div key={r.variant_id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="text-sm font-semibold text-white">{r.producto}{r.color?` · ${r.color}`:''}</p><p className="text-xs text-gray-400 mt-1">Stock numérico: <b>{r.stock_numerico}</b> · Seriales disponibles: <b>{r.seriales_disponibles}</b> · Diferencia: <b className="text-orange-300">{r.diferencia}</b></p></div><button onClick={()=>reconciliar(r)} disabled={fixing===r.variant_id} className="rounded-xl bg-orange-500/15 border border-orange-500/20 px-3 py-2 text-xs font-bold text-orange-200 disabled:opacity-40 inline-flex items-center gap-2"><ScanLine size={14}/>{fixing===r.variant_id?'Reconciliando...':'Reconciliar'}</button></div>)}</div></section>}
 <div className="grid xl:grid-cols-[1fr_360px] gap-4"><section className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden"><div className="p-4 border-b border-[#30363d]"><h2 className="text-sm font-bold text-white">Detalle</h2></div>{loading?<p className="p-8 text-center text-sm text-gray-500">Calculando...</p>:<div className="overflow-x-auto"><table className="w-full text-xs min-w-[650px]"><thead><tr className="text-gray-500 border-b border-[#30363d]"><th className="text-left p-3">Producto</th><th className="text-left p-3">Variante</th><th className="text-right p-3">Unidades</th><th className="text-right p-3">Costo</th><th className="text-right p-3">Valor</th></tr></thead><tbody className="divide-y divide-[#21262d]">{rows.map(r=><tr key={r.variant_id}><td className="p-3 text-white"><b>{r.producto}</b><p className="text-[10px] text-gray-600">{r.sku||'—'}</p></td><td className="p-3 text-gray-400">{r.color||'General'}</td><td className="p-3 text-right text-white">{r.cantidad}</td><td className="p-3 text-right text-gray-300">{money(r.costo_unitario)}</td><td className="p-3 text-right font-bold text-cyan-300">{money(r.valor_stock)}</td></tr>)}</tbody></table></div>}</section>
 <section className="rounded-2xl border border-[#30363d] bg-[#161b22] h-fit"><div className="p-4 border-b border-[#30363d] flex items-center gap-2"><History size={15} className="text-cyan-400"/><h2 className="text-sm font-bold text-white">Historial de costos</h2></div><div className="divide-y divide-[#21262d] max-h-[620px] overflow-y-auto">{hist.map(h=><div key={h.id} className="p-3"><p className="text-xs font-semibold text-white">{h.product?.nombre||'Producto'}</p><p className="text-[11px] text-gray-400 mt-1">{money(Number(h.costo_anterior||0))} → <b className="text-cyan-300">{money(h.costo_nuevo)}</b></p><div className="flex justify-between mt-1 text-[10px] text-gray-600"><span>{h.origen}</span><span>{new Date(h.created_at).toLocaleString('es-PE')}</span></div></div>)}{!hist.length&&<p className="p-8 text-center text-xs text-gray-600">Sin cambios de costo.</p>}</div></section></div></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#30363d] bg-[#161b22] p-4"><p className="text-[11px] text-gray-500">{label}</p><p className="text-xl font-bold text-white mt-1">{value}</p></div>}
