import { useEffect,useMemo,useState } from 'react'
import { MessageCircle,RefreshCw,Play,RotateCcw,XCircle,Plus } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useToast } from '../lib/toast'

type Plantilla={id:string;clave:string;nombre:string;meta_template_name:string|null;idioma:string;cuerpo_preview:string;activo:boolean}
type Envio={id:string;cliente_id:string;cliente_nombre:string;telefono:string;plantilla_clave:string;plantilla_nombre:string;variables:Record<string,unknown>;recurso_tipo:string|null;recurso_id:string|null;event_key:string;estado:string;meta_message_id:string|null;error:string|null;created_at:string;procesado_at:string|null;enviado_at:string|null}
type Cliente={id:string;nombre:string;telefono:string|null;consentimiento_whatsapp:boolean}
const stateClass=(e:string)=>e==='enviado'?'text-green-400':e==='fallido'?'text-red-400':e==='cancelado'?'text-gray-500':e==='procesando'?'text-cyan-400':'text-amber-300'

export default function WhatsAppAdmin(){
 const {showToast}=useToast();const [plantillas,setPlantillas]=useState<Plantilla[]>([]),[envios,setEnvios]=useState<Envio[]>([]),[clientes,setClientes]=useState<Cliente[]>([]),[estado,setEstado]=useState('todas'),[loading,setLoading]=useState(false),[processing,setProcessing]=useState(false),[editing,setEditing]=useState<Plantilla|null>(null),[open,setOpen]=useState(false),[clienteId,setClienteId]=useState(''),[plantillaClave,setPlantillaClave]=useState(''),[params,setParams]=useState('')
 const load=async()=>{setLoading(true);const [p,e,c]=await Promise.all([supabase.rpc('whatsapp_plantillas_admin'),supabase.rpc('whatsapp_outbox_admin',{p_estado:estado==='todas'?null:estado,p_limit:200}),supabase.rpc('clientes_segmentados_admin')]);setLoading(false);if(p.error||e.error||c.error){showToast('No se pudo cargar WhatsApp','error');return}setPlantillas((p.data as Plantilla[])||[]);setEnvios((e.data as Envio[])||[]);setClientes(((c.data as any[])||[]).map(x=>({id:x.id,nombre:x.nombre,telefono:x.telefono,consentimiento_whatsapp:Boolean(x.consentimiento_whatsapp)})))}
 useEffect(()=>{load()},[estado])
 const consentidos=useMemo(()=>clientes.filter(c=>c.telefono&&c.consentimiento_whatsapp),[clientes])
 const procesar=async()=>{setProcessing(true);const {data,error}=await supabase.functions.invoke('procesar-whatsapp-outbox',{body:{limit:50}});setProcessing(false);if(error){showToast(error.message,'error');return}const r=data as {enviados?:number;fallidos?:number};showToast(`WhatsApp: ${r?.enviados||0} enviado(s), ${r?.fallidos||0} fallido(s)`,'success');load()}
 const reintentar=async(id:string)=>{const {error}=await supabase.rpc('reintentar_whatsapp_admin',{p_id:id});if(error){showToast(error.message,'error');return}showToast('Envío devuelto a pendientes','success');load()}
 const cancelar=async(id:string)=>{const {error}=await supabase.rpc('cancelar_whatsapp_admin',{p_id:id});if(error){showToast(error.message,'error');return}showToast('Envío cancelado','success');load()}
 const encolar=async()=>{if(!clienteId||!plantillaClave)return;const values=params.split('|').map(x=>x.trim()).filter(Boolean);const {error}=await supabase.rpc('encolar_whatsapp_admin',{p_cliente_id:clienteId,p_plantilla_clave:plantillaClave,p_variables:{params:values},p_recurso_tipo:'manual',p_recurso_id:null,p_event_key:null});if(error){showToast(error.message,'error');return}showToast('Mensaje encolado','success');setClienteId('');setPlantillaClave('');setParams('');load()}
 return <div className="p-3 md:p-5 max-w-7xl mx-auto space-y-5">
  <div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><MessageCircle size={21} className="text-green-400"/><h1 className="text-xl font-bold text-white">WhatsApp</h1></div><p className="text-xs text-gray-500 mt-1">Plantillas oficiales, cola de salida, reintentos y trazabilidad.</p></div><div className="flex gap-2"><button onClick={()=>{setEditing(null);setOpen(true)}} className="rounded-xl border border-[#30363d] bg-[#161b22] px-3 py-2 text-xs text-gray-300"><Plus size={14} className="inline mr-1"/>Plantilla</button><button onClick={load} className="btn-secondary"><RefreshCw size={15}/></button><button onClick={procesar} disabled={processing} className="inline-flex items-center gap-2 rounded-xl bg-green-500 px-4 py-2 text-sm font-bold text-black disabled:opacity-50"><Play size={15}/>{processing?'Procesando...':'Procesar pendientes'}</button></div></div>
  <section className="rounded-2xl border border-[#30363d] bg-[#161b22] p-4"><h2 className="text-sm font-bold text-white mb-3">Envío manual</h2><div className="grid md:grid-cols-[1fr_1fr_1fr_auto] gap-2"><select value={clienteId} onChange={e=>setClienteId(e.target.value)} className="input-personal"><option value="">Cliente con consentimiento</option>{consentidos.map(c=><option key={c.id} value={c.id}>{c.nombre} · {c.telefono}</option>)}</select><select value={plantillaClave} onChange={e=>setPlantillaClave(e.target.value)} className="input-personal"><option value="">Plantilla</option>{plantillas.filter(p=>p.activo).map(p=><option key={p.id} value={p.clave}>{p.nombre}</option>)}</select><input value={params} onChange={e=>setParams(e.target.value)} placeholder="Parámetros separados por |" className="input-personal"/><button onClick={encolar} disabled={!clienteId||!plantillaClave} className="rounded-xl bg-cyan-500 px-4 text-sm font-bold text-black disabled:opacity-40">Encolar</button></div></section>
  <section className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden"><div className="p-4 border-b border-[#30363d] flex items-center justify-between"><div><h2 className="text-sm font-bold text-white">Plantillas</h2><p className="text-[11px] text-gray-600">Solo se envían plantillas con nombre Meta configurado.</p></div></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-2 p-3">{plantillas.map(p=><button key={p.id} onClick={()=>{setEditing(p);setOpen(true)}} className="text-left rounded-xl border border-[#21262d] bg-[#0d1117] p-3"><div className="flex justify-between gap-2"><p className="font-semibold text-white text-sm">{p.nombre}</p><span className={p.activo?'text-[10px] text-green-400':'text-[10px] text-gray-600'}>{p.activo?'Activa':'Inactiva'}</span></div><p className="text-[10px] text-cyan-400 mt-1">{p.clave} · {p.meta_template_name||'SIN META'}</p><p className="text-xs text-gray-500 mt-2 line-clamp-2">{p.cuerpo_preview}</p></button>)}</div></section>
  <section className="rounded-2xl border border-[#30363d] bg-[#161b22] overflow-hidden"><div className="p-4 border-b border-[#30363d] flex items-center justify-between gap-3"><h2 className="text-sm font-bold text-white">Outbox</h2><select value={estado} onChange={e=>setEstado(e.target.value)} className="input-personal"><option value="todas">Todos</option><option value="pendiente">Pendientes</option><option value="procesando">Procesando</option><option value="enviado">Enviados</option><option value="fallido">Fallidos</option><option value="cancelado">Cancelados</option></select></div>{loading?<p className="p-10 text-center text-sm text-gray-500">Cargando...</p>:envios.length===0?<p className="p-10 text-center text-sm text-gray-600">Sin envíos.</p>:<div className="divide-y divide-[#21262d]">{envios.map(e=><div key={e.id} className="p-4 flex flex-col lg:flex-row lg:items-center justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap gap-2 items-center"><p className="font-semibold text-white text-sm">{e.cliente_nombre}</p><span className={`text-[10px] uppercase font-bold ${stateClass(e.estado)}`}>{e.estado}</span></div><p className="text-xs text-gray-500">{e.telefono} · {e.plantilla_nombre} · {new Date(e.created_at).toLocaleString('es-PE')}</p>{e.meta_message_id&&<p className="text-[10px] text-green-500 mt-1">Meta: {e.meta_message_id}</p>}{e.error&&<p className="text-[11px] text-red-400 mt-1">{e.error}</p>}</div><div className="flex gap-2">{['fallido','cancelado'].includes(e.estado)&&<button onClick={()=>reintentar(e.id)} className="inline-flex items-center gap-1.5 rounded-lg border border-cyan-500/20 px-3 py-2 text-xs text-cyan-300"><RotateCcw size={13}/>Reintentar</button>}{e.estado==='pendiente'&&<button onClick={()=>cancelar(e.id)} className="inline-flex items-center gap-1.5 rounded-lg border border-red-500/20 px-3 py-2 text-xs text-red-300"><XCircle size={13}/>Cancelar</button>}</div></div>)}</div>}</section>
  {open&&<PlantillaModal value={editing} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}
 </div>
}

function PlantillaModal({value,onClose,onSaved}:{value:Plantilla|null;onClose:()=>void;onSaved:()=>void}){const {showToast}=useToast();const [clave,setClave]=useState(value?.clave||''),[nombre,setNombre]=useState(value?.nombre||''),[meta,setMeta]=useState(value?.meta_template_name||''),[idioma,setIdioma]=useState(value?.idioma||'es'),[preview,setPreview]=useState(value?.cuerpo_preview||''),[activo,setActivo]=useState(value?.activo??true),[saving,setSaving]=useState(false);const save=async()=>{setSaving(true);const {error}=await supabase.rpc('guardar_plantilla_whatsapp_admin',{p_id:value?.id||null,p_clave:clave,p_nombre:nombre,p_meta_template_name:meta||null,p_idioma:idioma,p_cuerpo_preview:preview,p_activo:activo});setSaving(false);if(error){showToast(error.message,'error');return}showToast('Plantilla guardada','success');onSaved()};return <div className="fixed inset-0 z-[70] bg-black/65 backdrop-blur-sm flex items-end md:items-center justify-center"><div className="w-full max-w-lg rounded-t-2xl md:rounded-2xl border border-[#30363d] bg-[#161b22] p-5"><h3 className="font-bold text-white mb-4">{value?'Editar plantilla':'Nueva plantilla'}</h3><div className="grid md:grid-cols-2 gap-2"><input value={clave} onChange={e=>setClave(e.target.value)} placeholder="clave interna" className="input-personal"/><input value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Nombre" className="input-personal"/><input value={meta} onChange={e=>setMeta(e.target.value)} placeholder="Nombre aprobado en Meta" className="input-personal"/><input value={idioma} onChange={e=>setIdioma(e.target.value)} placeholder="es" className="input-personal"/></div><textarea rows={4} value={preview} onChange={e=>setPreview(e.target.value)} placeholder="Vista previa del mensaje" className="input-personal w-full mt-2"/><label className="flex gap-2 items-center text-xs text-gray-400 mt-3"><input type="checkbox" checked={activo} onChange={e=>setActivo(e.target.checked)}/>Activa</label><div className="flex gap-2 mt-5"><button onClick={onClose} className="flex-1 rounded-xl border border-[#30363d] py-2.5 text-sm text-gray-300">Cancelar</button><button onClick={save} disabled={saving||clave.trim().length<2||nombre.trim().length<2||preview.trim().length<2} className="flex-1 rounded-xl bg-green-500 py-2.5 text-sm font-bold text-black disabled:opacity-40">{saving?'Guardando...':'Guardar'}</button></div></div></div>}
