import fs from 'node:fs'
const read=(p)=>fs.readFileSync(p,'utf8')
function assert(ok,msg){if(!ok){console.error(`FAIL: ${msg}`);process.exitCode=1}else console.log(`PASS: ${msg}`)}
const app=read('src/App.tsx')
const layout=read('src/components/Layout.tsx')
const health=read('src/pages/EstadoSistema.tsx')
const migration=read('supabase/migrations/20260824191128_admin_release_health_check.sql')
const ci=read('.github/workflows/ci.yml')
const vercel=JSON.parse(read('vercel.json'))
const inventario=read('src/pages/Inventario.tsx')
assert(app.includes('path="estado-sistema" element={<AdminRoute><EstadoSistema /></AdminRoute>}'),'Estado del sistema está protegido por AdminRoute')
assert(layout.includes("to:'/estado-sistema'"),'Estado del sistema está en navegación administrativa')
assert(health.includes("supabase.rpc('release_health_admin')"),'Health UI usa RPC administrativa')
assert(migration.includes('revoke execute on function public.release_health_admin() from public,anon'),'Health RPC no es ejecutable por anon')
assert(migration.includes('private.auth_is_admin()'),'Health RPC exige contexto administrador')
assert(ci.includes('permissions:\n  contents: read'),'CI usa permisos mínimos')
assert(ci.includes('cancel-in-progress: true'),'CI cancela ejecuciones obsoletas')
assert(ci.includes('actions/upload-artifact@v4'),'CI conserva artefacto de build validado')
assert(ci.includes('path: dist'),'CI sube dist como artefacto')
assert(vercel?.git?.deploymentEnabled?.main===true,'Vercel permite deployment de main')
assert(Object.keys(vercel?.git?.deploymentEnabled||{}).length===1,'Vercel no habilita ramas de trabajo explícitamente')
assert(!inventario.includes("product:products(id, nombre, sku, imagen_url, costo"),'Inventario operativo no solicita costo directamente')
assert(inventario.includes("supabase.rpc('costos_productos_admin')"),'Costos se cargan mediante RPC administrativa')
if(process.exitCode)process.exit(process.exitCode)
console.log('Release readiness regression checks passed.')
