create table if not exists public.personal_solicitudes(
 id uuid primary key default gen_random_uuid(),
 staff_id uuid not null references public.staff(id) on delete cascade,
 location_id uuid not null references public.locations(id) on delete restrict,
 tipo text not null check(tipo in('permiso','vacaciones','licencia','cambio_turno')),
 fecha_desde date not null,
 fecha_hasta date not null,
 turno_id uuid references public.turnos(id) on delete restrict,
 motivo text not null,
 documento_path text,
 estado text not null default 'pendiente' check(estado in('pendiente','aprobada','rechazada','cancelada')),
 resuelto_por uuid references public.staff(id) on delete set null,
 resolucion_motivo text,
 created_at timestamptz not null default now(),
 resolved_at timestamptz,
 constraint personal_solicitudes_fechas check(fecha_hasta>=fecha_desde),
 constraint personal_solicitudes_cambio_fecha check(tipo<>'cambio_turno' or fecha_desde=fecha_hasta)
);
create table if not exists public.personal_documentos(
 id uuid primary key default gen_random_uuid(),staff_id uuid not null references public.staff(id) on delete cascade,
 tipo text not null default 'otro' check(tipo in('dni','contrato','certificado','constancia','sustento','otro')),
 nombre text not null,storage_path text not null unique,mime_type text,size_bytes bigint,vence_el date,observacion text,uploaded_by uuid references public.staff(id) on delete set null,created_at timestamptz not null default now()
);
alter table public.personal_solicitudes enable row level security;
alter table public.personal_documentos enable row level security;
create policy personal_solicitudes_read on public.personal_solicitudes for select to authenticated using(private.auth_is_admin() or staff_id=private.auth_staff_id());
create policy personal_documentos_read on public.personal_documentos for select to authenticated using(private.auth_is_admin() or staff_id=private.auth_staff_id());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('personal-documentos','personal-documentos',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy personal_docs_read on storage.objects for select to authenticated using(bucket_id='personal-documentos' and (private.auth_is_admin() or split_part(name,'/',1)=private.auth_staff_id()::text));
create policy personal_docs_insert on storage.objects for insert to authenticated with check(bucket_id='personal-documentos' and (private.auth_is_admin() or split_part(name,'/',1)=private.auth_staff_id()::text));
create policy personal_docs_update on storage.objects for update to authenticated using(bucket_id='personal-documentos' and (private.auth_is_admin() or split_part(name,'/',1)=private.auth_staff_id()::text)) with check(bucket_id='personal-documentos' and (private.auth_is_admin() or split_part(name,'/',1)=private.auth_staff_id()::text));
create policy personal_docs_delete on storage.objects for delete to authenticated using(bucket_id='personal-documentos' and (private.auth_is_admin() or split_part(name,'/',1)=private.auth_staff_id()::text));
create or replace function public.crear_solicitud_personal(p_tipo text,p_fecha_desde date,p_fecha_hasta date,p_motivo text,p_turno_id uuid default null,p_documento_path text default null) returns uuid language plpgsql security definer set search_path='public','private' as $$ declare actor public.staff; rid uuid; begin select * into actor from public.staff where id=private.auth_staff_id() and activo=true; if actor.id is null then raise exception 'Personal no válido o inactivo'; end if; if p_tipo not in ('permiso','vacaciones','licencia','cambio_turno') then raise exception 'Tipo de solicitud inválido'; end if; if p_fecha_desde is null or p_fecha_hasta is null or p_fecha_hasta<p_fecha_desde then raise exception 'Rango de fechas inválido'; end if; if p_tipo='cambio_turno' and p_fecha_desde<>p_fecha_hasta then raise exception 'El cambio de turno debe ser para una sola fecha'; end if; if length(trim(coalesce(p_motivo,'')))<3 then raise exception 'Motivo demasiado corto'; end if; if p_documento_path is not null and split_part(p_documento_path,'/',1)<>actor.id::text and not private.auth_is_admin() then raise exception 'Documento fuera de la carpeta del usuario'; end if; insert into public.personal_solicitudes(staff_id,location_id,tipo,fecha_desde,fecha_hasta,turno_id,motivo,documento_path) values(actor.id,private.auth_location_id(),p_tipo,p_fecha_desde,p_fecha_hasta,p_turno_id,trim(p_motivo),nullif(trim(coalesce(p_documento_path,'')),'')) returning id into rid; insert into public.notificaciones(location_id,tipo,titulo,mensaje,prioridad,recurso_tipo,recurso_id,event_key) values(private.auth_location_id(),'solicitud_personal','Nueva solicitud de personal',actor.nombre||' solicitó '||replace(p_tipo,'_',' ')||' del '||p_fecha_desde||' al '||p_fecha_hasta,'media','personal_solicitud',rid,'solicitud-personal:'||rid) on conflict(event_key) do nothing; return rid; end$$;
create or replace function public.mis_solicitudes_personal(p_limit integer default 50) returns setof public.personal_solicitudes language sql stable security definer set search_path='public','private' as $$ select s.* from public.personal_solicitudes s where s.staff_id=private.auth_staff_id() order by s.created_at desc limit greatest(1,least(coalesce(p_limit,50),200)); $$;
create or replace function public.solicitudes_personal_admin(p_estado text default null,p_limit integer default 100) returns table(id uuid,staff_id uuid,nombre text,username text,puesto text,tipo text,fecha_desde date,fecha_hasta date,turno_id uuid,turno_nombre text,motivo text,documento_path text,estado text,resolucion_motivo text,created_at timestamptz,resolved_at timestamptz) language sql stable security definer set search_path='public','private' as $$ select s.id,s.staff_id,st.nombre,st.username,st.puesto,s.tipo,s.fecha_desde,s.fecha_hasta,s.turno_id,t.nombre,s.motivo,s.documento_path,s.estado,s.resolucion_motivo,s.created_at,s.resolved_at from public.personal_solicitudes s join public.staff st on st.id=s.staff_id left join public.turnos t on t.id=s.turno_id where private.auth_is_admin() and (p_estado is null or s.estado=p_estado) order by case s.estado when 'pendiente' then 0 else 1 end,s.created_at desc limit greatest(1,least(coalesce(p_limit,100),500)); $$;
create or replace function public.resolver_solicitud_personal_admin(p_id uuid,p_aprobar boolean,p_motivo text default null) returns boolean language plpgsql security definer set search_path='public','private' as $$ declare req public.personal_solicitudes; actor uuid:=private.auth_staff_id(); begin if not private.auth_is_admin() then raise exception 'Solo administración'; end if; select * into req from public.personal_solicitudes where id=p_id for update; if req.id is null then raise exception 'Solicitud inexistente'; end if; if req.estado<>'pendiente' then raise exception 'La solicitud ya fue resuelta'; end if; if coalesce(p_aprobar,false) then if req.tipo in ('permiso','vacaciones','licencia') then insert into public.personal_permisos(staff_id,tipo,fecha_desde,fecha_hasta,motivo,activo,registrado_por) values(req.staff_id,req.tipo,req.fecha_desde,req.fecha_hasta,'Solicitud aprobada: '||req.motivo,true,actor); elsif req.tipo='cambio_turno' then update public.staff_turno_excepciones set activo=false,updated_at=now() where staff_id=req.staff_id and fecha=req.fecha_desde and activo=true; insert into public.staff_turno_excepciones(staff_id,fecha,turno_id,motivo,activo,registrado_por) values(req.staff_id,req.fecha_desde,req.turno_id,'Solicitud aprobada: '||req.motivo,true,actor); end if; update public.personal_solicitudes set estado='aprobada',resuelto_por=actor,resolucion_motivo=nullif(trim(coalesce(p_motivo,'')),''),resolved_at=now() where id=req.id; else update public.personal_solicitudes set estado='rechazada',resuelto_por=actor,resolucion_motivo=coalesce(nullif(trim(coalesce(p_motivo,'')),''),'Solicitud rechazada'),resolved_at=now() where id=req.id; end if; insert into public.notificaciones(staff_id,location_id,tipo,titulo,mensaje,prioridad,recurso_tipo,recurso_id,event_key) values(req.staff_id,req.location_id,'solicitud_personal_resuelta',case when p_aprobar then 'Solicitud aprobada' else 'Solicitud rechazada' end,'Tu solicitud de '||replace(req.tipo,'_',' ')||' fue '||case when p_aprobar then 'aprobada' else 'rechazada' end,'media','personal_solicitud',req.id,'solicitud-resuelta:'||req.id) on conflict(event_key) do nothing; return true; end$$;
create or replace function public.cancelar_mi_solicitud_personal(p_id uuid) returns boolean language plpgsql security definer set search_path='public','private' as $$ begin update public.personal_solicitudes set estado='cancelada' where id=p_id and staff_id=private.auth_staff_id() and estado='pendiente'; return found; end$$;
create or replace function public.registrar_documento_personal(p_staff_id uuid,p_tipo text,p_nombre text,p_storage_path text,p_mime_type text default null,p_size_bytes bigint default null,p_vence_el date default null,p_observacion text default null) returns uuid language plpgsql security definer set search_path='public','private' as $$ declare actor uuid:=private.auth_staff_id(); rid uuid; begin if actor is null then raise exception 'No autenticado'; end if; if not private.auth_is_admin() and p_staff_id<>actor then raise exception 'Sin permiso'; end if; if split_part(p_storage_path,'/',1)<>p_staff_id::text then raise exception 'Ruta de documento inválida'; end if; if p_tipo not in ('dni','contrato','certificado','constancia','sustento','otro') then raise exception 'Tipo de documento inválido'; end if; insert into public.personal_documentos(staff_id,tipo,nombre,storage_path,mime_type,size_bytes,vence_el,observacion,uploaded_by) values(p_staff_id,p_tipo,trim(p_nombre),p_storage_path,p_mime_type,p_size_bytes,p_vence_el,nullif(trim(coalesce(p_observacion,'')),''),actor) returning id into rid; return rid; end$$;
create or replace function public.documentos_personal(p_staff_id uuid default null) returns setof public.personal_documentos language sql stable security definer set search_path='public','private' as $$ select d.* from public.personal_documentos d where d.staff_id=case when private.auth_is_admin() and p_staff_id is not null then p_staff_id else private.auth_staff_id() end order by d.created_at desc; $$;
revoke execute on function public.crear_solicitud_personal(text,date,date,text,uuid,text) from public,anon; revoke execute on function public.mis_solicitudes_personal(integer) from public,anon; revoke execute on function public.solicitudes_personal_admin(text,integer) from public,anon; revoke execute on function public.resolver_solicitud_personal_admin(uuid,boolean,text) from public,anon; revoke execute on function public.cancelar_mi_solicitud_personal(uuid) from public,anon; revoke execute on function public.registrar_documento_personal(uuid,text,text,text,text,bigint,date,text) from public,anon; revoke execute on function public.documentos_personal(uuid) from public,anon;
grant execute on function public.crear_solicitud_personal(text,date,date,text,uuid,text) to authenticated; grant execute on function public.mis_solicitudes_personal(integer) to authenticated; grant execute on function public.solicitudes_personal_admin(text,integer) to authenticated; grant execute on function public.resolver_solicitud_personal_admin(uuid,boolean,text) to authenticated; grant execute on function public.cancelar_mi_solicitud_personal(uuid) to authenticated; grant execute on function public.registrar_documento_personal(uuid,text,text,text,text,bigint,date,text) to authenticated; grant execute on function public.documentos_personal(uuid) to authenticated;