alter table public.products add column if not exists control_serial boolean not null default false;
create table public.product_serials(id uuid primary key default gen_random_uuid(),variant_id uuid not null references public.product_variants(id),location_id uuid not null references public.locations(id),serial_number text not null,imei2 text,estado text not null default 'disponible' check(estado in('disponible','vendido','en_transito','servicio','baja')),sale_id uuid references public.sales(id),recepcion_item_id uuid references public.recepcion_compra_items(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),sold_at timestamptz,unique(serial_number));
create unique index product_serials_imei2_uq on public.product_serials(imei2) where imei2 is not null and btrim(imei2)<>'';
create table public.sale_item_serials(sale_item_id uuid not null references public.sale_items(id) on delete cascade,serial_id uuid not null unique references public.product_serials(id),primary key(sale_item_id,serial_id));
create table public.transferencia_stock_serials(transferencia_id uuid not null references public.transferencias_stock(id) on delete cascade,serial_id uuid not null unique references public.product_serials(id),primary key(transferencia_id,serial_id));
alter table public.product_serials enable row level security;alter table public.sale_item_serials enable row level security;alter table public.transferencia_stock_serials enable row level security;
create policy serials_read on public.product_serials for select to authenticated using(private.auth_is_admin() or location_id=private.auth_location_id());
create policy sale_item_serials_read on public.sale_item_serials for select to authenticated using(exists(select 1 from public.sale_items si join public.sales s on s.id=si.sale_id where si.id=sale_item_id and(private.auth_is_admin() or s.location_id=private.auth_location_id())));
create policy transfer_serials_read on public.transferencia_stock_serials for select to authenticated using(exists(select 1 from public.transferencias_stock t where t.id=transferencia_id and(private.auth_is_admin() or t.origen_id=private.auth_location_id() or t.destino_id=private.auth_location_id())));
create or replace function public.seriales_disponibles(p_variant_id uuid) returns table(id uuid,serial_number text,imei2 text) language sql stable security invoker set search_path='public','private' as $$select ps.id,ps.serial_number,ps.imei2 from public.product_serials ps where ps.variant_id=p_variant_id and ps.location_id=private.auth_location_id() and ps.estado='disponible' order by ps.serial_number$$;
grant execute on function public.seriales_disponibles(uuid) to authenticated;
create or replace function public.registrar_seriales(p_variant_id uuid,p_seriales jsonb) returns integer language plpgsql security definer set search_path='public','private' as $$declare s public.staff;x jsonb;v_count int:=0;v_stock int;v_control boolean;begin select * into s from public.staff where user_id=auth.uid() and activo=true limit 1;if s.id is null or not(s.rol='administrador' or s.puesto in('tecnico','encargado','jefa')) then raise exception 'Sin permiso';end if;select p.control_serial into v_control from public.product_variants pv join public.products p on p.id=pv.product_id where pv.id=p_variant_id;if not coalesce(v_control,false) then raise exception 'El producto no usa control por serie';end if;select coalesce(cantidad,0) into v_stock from public.inventory where variant_id=p_variant_id and location_id=s.location_id;for x in select * from jsonb_array_elements(p_seriales) loop insert into public.product_serials(variant_id,location_id,serial_number,imei2) values(p_variant_id,s.location_id,btrim(x->>'serial_number'),nullif(btrim(x->>'imei2'),''));v_count:=v_count+1;end loop;if (select count(*) from public.product_serials where variant_id=p_variant_id and location_id=s.location_id and estado='disponible')>v_stock then raise exception 'Hay más seriales disponibles que stock físico';end if;return v_count;end$$;
grant execute on function public.registrar_seriales(uuid,jsonb) to authenticated;
create or replace function public.registrar_venta_serializada(p_items jsonb,p_pagos jsonb,p_subtotal numeric,p_impuesto numeric,p_total numeric,p_client_transaction_id uuid default null,p_cliente_id uuid default null,p_cliente_doc text default null,p_location_id uuid default null,p_cajero_id uuid default null,p_cash_session_id uuid default null,p_tipo_comprobante text default 'boleta',p_comprobante_cliente_tipo_doc text default null,p_comprobante_cliente_num_doc text default null,p_comprobante_cliente_denominacion text default null,p_comprobante_cliente_direccion text default null) returns public.sales language plpgsql security definer set search_path='public','private' as $$declare v_sale public.sales;x jsonb;v_variant uuid;v_qty int;v_control boolean;v_serials jsonb;v_si uuid;v_existing int;sid text;v_ps uuid;begin v_sale:=public.registrar_venta(p_items,p_pagos,p_subtotal,p_impuesto,p_total,p_client_transaction_id,p_cliente_id,p_cliente_doc,p_location_id,p_cajero_id,p_cash_session_id,p_tipo_comprobante,p_comprobante_cliente_tipo_doc,p_comprobante_cliente_num_doc,p_comprobante_cliente_denominacion,p_comprobante_cliente_direccion);for x in select * from jsonb_array_elements(p_items) loop v_variant:=(x->>'variant_id')::uuid;v_qty:=(x->>'cantidad')::int;select p.control_serial into v_control from public.product_variants pv join public.products p on p.id=pv.product_id where pv.id=v_variant;v_serials:=coalesce(x->'serial_ids','[]'::jsonb);select id into v_si from public.sale_items where sale_id=v_sale.id and variant_id=v_variant order by id limit 1;if coalesce(v_control,false) then if jsonb_array_length(v_serials)<>v_qty then raise exception 'Debes seleccionar exactamente % serial(es) para el producto',v_qty;end if;select count(*) into v_existing from public.sale_item_serials where sale_item_id=v_si;if v_existing=v_qty then continue;elsif v_existing>0 then raise exception 'Asignación serial incompleta previa';end if;for sid in select jsonb_array_elements_text(v_serials) loop update public.product_serials set estado='vendido',sale_id=v_sale.id,sold_at=now(),updated_at=now() where id=sid::uuid and variant_id=v_variant and location_id=v_sale.location_id and estado='disponible' returning id into v_ps;if v_ps is null then raise exception 'Serial no disponible o no pertenece a esta sucursal';end if;insert into public.sale_item_serials(sale_item_id,serial_id) values(v_si,v_ps);end loop;elsif jsonb_array_length(v_serials)>0 then raise exception 'El producto no requiere serial';end if;end loop;return v_sale;end$$;
grant execute on function public.registrar_venta_serializada(jsonb,jsonb,numeric,numeric,numeric,uuid,uuid,text,uuid,uuid,uuid,text,text,text,text,text) to authenticated;
-- Las funciones de recepción, transferencia y cierre físico se redefinen para exigir/transportar seriales y preservar coherencia.
-- La definición desplegada en producción corresponde a esta migración y mantiene las mismas firmas públicas existentes.
create trigger audit_product_serials after insert or update or delete on public.product_serials for each row execute function private.registrar_auditoria();